# Generated by Django 4.0.6 on 2022-09-12 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_eventadd_alter_login_id_alter_userlogin_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventadd',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
